version: '2.1'
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@4.1.0
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - node/test
      - eb/deploy:
          environment-name: my-app-env
          filters:
            branches:
              only:
                - circleci-project-setup
          
          requires:
            - node/test