version: '2.1'
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@4.1.0
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - node/test
      - eb/deploy:
          context: aws-creds
          environment-name: my-app
          filters:
            branches:
              only:
                - circleci-project-setup
          label: version-<<pipeline.number>>
          requires:
            - node/test